/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ru.otus.kotlin.brown.api.log.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param message 
 * @param `field` 
 * @param code 
 * @param level 
 */
@Serializable

data class ErrorLogModel (

    @SerialName(value = "message") val message: kotlin.String? = null,

    @SerialName(value = "field") val `field`: kotlin.String? = null,

    @SerialName(value = "code") val code: kotlin.String? = null,

    @SerialName(value = "level") val level: kotlin.String? = null

)

