/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ru.otus.kotlin.brown.api.log.models

import ru.otus.kotlin.brown.api.log.models.NotificationFilterLog
import ru.otus.kotlin.brown.api.log.models.NotificationLog

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param requestId 
 * @param operation 
 * @param requestNotification 
 * @param requestFilter 
 * @param responseNotification 
 * @param responseNotificationList 
 */
@Serializable

data class NotificationLogModel (

    @SerialName(value = "requestId") val requestId: kotlin.String? = null,

    @SerialName(value = "operation") val operation: NotificationLogModel.Operation? = null,

    @SerialName(value = "requestNotification") val requestNotification: NotificationLog? = null,

    @SerialName(value = "requestFilter") val requestFilter: NotificationFilterLog? = null,

    @SerialName(value = "responseNotification") val responseNotification: NotificationLog? = null,

    @SerialName(value = "responseNotificationList") val responseNotificationList: kotlin.collections.List<NotificationLog>? = null

) {

    /**
     * 
     *
     * Values: CREATE,READ,UPDATE,CANCEL,SEARCH
     */
    @Serializable
    enum class Operation(val value: kotlin.String) {
        @SerialName(value = "create") CREATE("create"),
        @SerialName(value = "read") READ("read"),
        @SerialName(value = "update") UPDATE("update"),
        @SerialName(value = "cancel") CANCEL("cancel"),
        @SerialName(value = "search") SEARCH("search");
    }
}

