/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ru.otus.kotlin.brown.api.log.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param searchString 
 * @param ownerId 
 * @param notificationType 
 */
@Serializable

data class NotificationFilterLog (

    @SerialName(value = "searchString") val searchString: kotlin.String? = null,

    @SerialName(value = "ownerId") val ownerId: kotlin.String? = null,

    @SerialName(value = "notificationType") val notificationType: kotlin.String? = null

)

