/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ru.otus.kotlin.brown.api.v1.models

import ru.otus.kotlin.brown.api.v1.models.NotificationDebug

import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.annotation.JsonSubTypes
import com.fasterxml.jackson.annotation.JsonTypeInfo

/**
 * Base interface for all requests
 *
 * @param requestType Discriminator string
 * @param requestId Request identifier for logging/debugging purposes (generated at client side)
 * @param debug 
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "requestType", visible = true)
@JsonSubTypes(
    JsonSubTypes.Type(value = NotificationCancelRequest::class, name = "cancel"),
    JsonSubTypes.Type(value = NotificationCreateRequest::class, name = "create"),
    JsonSubTypes.Type(value = NotificationReadRequest::class, name = "read"),
    JsonSubTypes.Type(value = NotificationSearchRequest::class, name = "search"),
    JsonSubTypes.Type(value = NotificationUpdateRequest::class, name = "update")
)

interface IRequest {

    /* Discriminator string */
    @get:JsonProperty("requestType")
    val requestType: kotlin.String
    /* Request identifier for logging/debugging purposes (generated at client side) */
    @get:JsonProperty("requestId")
    val requestId: kotlin.String?
    @get:JsonProperty("debug")
    val debug: NotificationDebug?
}

