/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ru.otus.kotlin.brown.api.v1.models

import ru.otus.kotlin.brown.api.v1.models.Error
import ru.otus.kotlin.brown.api.v1.models.ResponseResult

import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.annotation.JsonSubTypes
import com.fasterxml.jackson.annotation.JsonTypeInfo

/**
 * Base interface for all responses
 *
 * @param responseType Discriminator string
 * @param requestId Request identifier for logging/debugging purposes
 * @param result 
 * @param errors 
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "responseType", visible = true)
@JsonSubTypes(
    JsonSubTypes.Type(value = NotificationCancelResponse::class, name = "cancel"),
    JsonSubTypes.Type(value = NotificationCreateResponse::class, name = "create"),
    JsonSubTypes.Type(value = NotificationInitResponse::class, name = "init"),
    JsonSubTypes.Type(value = NotificationReadResponse::class, name = "read"),
    JsonSubTypes.Type(value = NotificationSearchResponse::class, name = "search"),
    JsonSubTypes.Type(value = NotificationUpdateResponse::class, name = "update")
)

interface IResponse {

    /* Discriminator string */
    @get:JsonProperty("responseType")
    val responseType: kotlin.String
    /* Request identifier for logging/debugging purposes */
    @get:JsonProperty("requestId")
    val requestId: kotlin.String?
    @get:JsonProperty("result")
    val result: ResponseResult?
    @get:JsonProperty("errors")
    val errors: kotlin.collections.List<Error>?
}

