/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ru.otus.kotlin.brown.api.v1.models

import ru.otus.kotlin.brown.api.v1.models.NotificationPermissions
import ru.otus.kotlin.brown.api.v1.models.NotificationType
import ru.otus.kotlin.brown.api.v1.models.NotificationVisibility

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param title Notification Title
 * @param description Notification Description
 * @param notificationType 
 * @param visibility 
 * @param id 
 * @param ownerId 
 * @param lock Optimistic lock version
 * @param permissions 
 */


data class NotificationResponseObject (

    /* Notification Title */
    @field:JsonProperty("title")
    val title: kotlin.String? = null,

    /* Notification Description */
    @field:JsonProperty("description")
    val description: kotlin.String? = null,

    @field:JsonProperty("notificationType")
    val notificationType: NotificationType? = null,

    @field:JsonProperty("visibility")
    val visibility: NotificationVisibility? = null,

    @field:JsonProperty("id")
    val id: kotlin.String? = null,

    @field:JsonProperty("ownerId")
    val ownerId: kotlin.String? = null,

    /* Optimistic lock version */
    @field:JsonProperty("lock")
    val lock: kotlin.String? = null,

    @field:JsonProperty("permissions")
    val permissions: kotlin.collections.Set<NotificationPermissions>? = null

)

