/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ru.otus.kotlin.brown.api.v1.models

import ru.otus.kotlin.brown.api.v1.models.NotificationResponseObject

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param notification 
 */


data class NotificationResponseSingle (

    @field:JsonProperty("notification")
    val notification: NotificationResponseObject? = null

)

