/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ru.otus.kotlin.brown.api.v1.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Search filter
 *
 * @param searchString Search string
 */


data class NotificationSearchFilter (

    /* Search string */
    @field:JsonProperty("searchString")
    val searchString: kotlin.String? = null

)

