/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ru.otus.kotlin.brown.api.v1.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Notification visibility
 *
 * Values: PRIVATE,PUBLIC
 */

enum class NotificationVisibility(val value: kotlin.String) {

    @JsonProperty(value = "private")
    PRIVATE("private"),

    @JsonProperty(value = "public")
    PUBLIC("public");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is NotificationVisibility) "$data" else null

        /**
         * Returns a valid [NotificationVisibility] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): NotificationVisibility? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

