/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ru.otus.kotlin.brown.api.v1.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param id 
 * @param lock Optimistic lock version
 */


data class NotificationCancelObject (

    @field:JsonProperty("id")
    val id: kotlin.String? = null,

    /* Optimistic lock version */
    @field:JsonProperty("lock")
    val lock: kotlin.String? = null

)

