/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ru.otus.kotlin.brown.api.v1.models

import ru.otus.kotlin.brown.api.v1.models.NotificationDebug

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param debug 
 */


data class NotificationRequestDebug (

    @field:JsonProperty("debug")
    val debug: NotificationDebug? = null

)

