openapi: 3.0.3
info:
  title: Brown log models
  description: Log models for logging Brown services
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.1
paths: {}

components:
  schemas:
    CommonLogModel:
      title: Common logging model
      description: Common model for logging of all microservices
      type: object
      properties:
        messageTime:
          type: string
        logId:
          type: string
        source:
          type: string
        notification:
          $ref: '#/components/schemas/NotificationLogModel'
        errors:
          type: array
          items:
            $ref: '#/components/schemas/ErrorLogModel'

    NotificationLogModel:
      title: Logging model for Notification microservice
      type: object
      properties:
        requestId:
          type: string
        operation:
          type: string
          enum:
            - create
            - read
            - update
            - cancel
            - search
        requestNotification:
          $ref: '#/components/schemas/NotificationLog'
        requestFilter:
          $ref: '#/components/schemas/NotificationFilterLog'
        responseNotification:
          $ref: '#/components/schemas/NotificationLog'
        responseNotificationList:
          type: array
          items:
            $ref: '#/components/schemas/NotificationLog'

    ErrorLogModel:
      title: Model for error logging
      type: object
      properties:
        message:
          type: string
        field:
          type: string
        code:
          type: string
        level:
          type: string

    NotificationLog:
      title: Model for Notification logging
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        description:
          type: string
        type:
          type: string
        visibility:
          type: string
        ownerId:
          type: string
        permissions:
          type: array
          uniqueItems: true
          items:
            type: string

    NotificationFilterLog:
      title: Model for Filter logging
      properties:
        searchString:
          type: string
        ownerId:
          type: string
        type:
          type: string

