openapi: 3.0.3
info:
  title: "Browser Notifications ${VERSION_APP}"
  description: Browser notifications for web-app users in real time
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.1.1
servers:
  - url: http://localhost:8080/api/v1
tags:
  - name: notification
paths:
  /notification/create:
    post:
      tags:
        - notification
      summary: Create notification
      operationId: notificationCreate
      requestBody:
        description: Request body
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NotificationCreateRequest'
        required: true
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotificationCreateResponse'
  /notification/read:
    post:
      tags:
        - notification
      summary: Read notification
      operationId: notificationRead
      requestBody:
        description: Request body
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NotificationReadRequest'
        required: true
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotificationReadResponse'
  /notification/update:
    post:
      tags:
        - notification
      summary: Update notification
      operationId: notificationUpdate
      requestBody:
        description: Request body
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NotificationUpdateRequest'
        required: true
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotificationUpdateResponse'
  /notification/cancel:
    post:
      tags:
        - notification
      summary: Cancel notification
      operationId: notificationCancel
      requestBody:
        description: Request body
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NotificationCancelRequest'
        required: true
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotificationCancelResponse'
  /notification/search:
    post:
      tags:
        - notification
      summary: Search notification
      operationId: notificationSearch
      requestBody:
        description: Request body
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NotificationSearchRequest'
        required: true
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotificationSearchResponse'

components:
  schemas:

    IRequest:
      type: object
      description: Base interface for all requests
      properties:
        requestType:
          type: string
          description: Discriminator string
          example: create
        requestId:
          type: string
          description: Request identifier for logging/debugging purposes (generated at client side)
        debug:
          $ref: '#/components/schemas/NotificationDebug'
      required:
        - requestType
      discriminator:
        propertyName: requestType
        mapping:
          create: '#/components/schemas/NotificationCreateRequest'
          read: '#/components/schemas/NotificationReadRequest'
          update: '#/components/schemas/NotificationUpdateRequest'
          cancel: '#/components/schemas/NotificationCancelRequest'
          search: '#/components/schemas/NotificationSearchRequest'

    Error:
      type: object
      properties:
        code:
          type: string
        group:
          type: string
        field:
          type: string
        message:
          type: string

    ResponseResult:
      type: string
      enum:
        - success
        - error

    IResponse:
      type: object
      description: Base interface for all responses
      properties:
        responseType:
          type: string
          description: Discriminator string
          example: create
        requestId:
          type: string
          description: Request identifier for logging/debugging purposes
        result:
          $ref: '#/components/schemas/ResponseResult'
        errors:
          type: array
          items:
            $ref: '#/components/schemas/Error'
      required:
        - responseType

      discriminator:
        propertyName: responseType
        mapping:
          create: '#/components/schemas/NotificationCreateResponse'
          read: '#/components/schemas/NotificationReadResponse'
          update: '#/components/schemas/NotificationUpdateResponse'
          cancel: '#/components/schemas/NotificationCancelResponse'
          search: '#/components/schemas/NotificationSearchResponse'
          init: '#/components/schemas/NotificationInitResponse'

    UserId:
      type: string
    NotificationId:
      type: string
    NotificationLock:
      type: string
      description: Optimistic lock version

    BaseNotification:
      type: object
      description: Object contains common properties for create and update type notifications
      properties:
        title:
          type: string
          description: Notification Title
        description:
          type: string
          description: Notification Description
        type:
          $ref: '#/components/schemas/NotificationType'
        status:
          $ref: '#/components/schemas/NotificationStatus'
        visibility:
          $ref: '#/components/schemas/NotificationVisibility'

    NotificationType:
      type: string
      description: 'Notification Type'
      enum:
        - common
        - warning
        - alert

    NotificationStatus:
      type: string
      description: 'Notification Status'
      enum:
        - open
        - closed

    NotificationVisibility:
      type: string
      description: 'Notification visibility'
      enum:
        - private
        - public

    NotificationInitResponse:
      allOf:
        - $ref: '#/components/schemas/IResponse'

    NotificationCreateObject:
      allOf:
        - $ref: '#/components/schemas/BaseNotification'

    NotificationCreateRequest:
      allOf:
        - $ref: '#/components/schemas/IRequest'
        - type: object
          properties:
            notification:
              $ref: '#/components/schemas/NotificationCreateObject'

    NotificationReadObject:
      allOf:
        - type: object
          properties:
            id:
              $ref: '#/components/schemas/NotificationId'

    NotificationReadRequest:
      allOf:
        - $ref: '#/components/schemas/IRequest'
        - type: object
          properties:
            notification:
              $ref: '#/components/schemas/NotificationReadObject'

    NotificationUpdateObject:
      allOf:
        - $ref: '#/components/schemas/BaseNotification'
        - type: object
          properties:
            id:
              $ref: '#/components/schemas/NotificationId'
            lock:
              $ref: '#/components/schemas/NotificationLock'

    NotificationUpdateRequest:
      allOf:
        - $ref: '#/components/schemas/IRequest'
        - type: object
          properties:
            notification:
              $ref: '#/components/schemas/NotificationUpdateObject'

    NotificationCancelObject:
      allOf:
        - type: object
          properties:
            id:
              $ref: '#/components/schemas/NotificationId'
            lock:
              $ref: '#/components/schemas/NotificationLock'

    NotificationCancelRequest:
      allOf:
        - $ref: '#/components/schemas/IRequest'
        - type: object
          properties:
            notification:
              $ref: '#/components/schemas/NotificationCancelObject'

    NotificationSearchFilter:
      type: object
      description: Search filter
      properties:
        searchString:
          type: string
          description: Search string

    NotificationSearchRequest:
      allOf:
        - $ref: '#/components/schemas/IRequest'
        - type: object
          properties:
            notificationFilter:
              $ref: '#/components/schemas/NotificationSearchFilter'

    NotificationResponseObject:
      allOf:
        - $ref: '#/components/schemas/BaseNotification'
        - type: object
          description: Object to output from backend
          properties:
            id:
              $ref: '#/components/schemas/NotificationId'
            ownerId:
              $ref: '#/components/schemas/UserId'
            lock:
              $ref: '#/components/schemas/NotificationLock'
            permissions:
              type: array
              uniqueItems: true
              items:
                $ref: '#/components/schemas/NotificationPermissions'

    NotificationPermissions:
      type: string
      description: Client permissions to access operations on notifications
      enum:
        - read
        - update
        - cancel
        - makeVisiblePublic

    NotificationResponseSingle:
      allOf:
        - type: object
          description: Response with single notification object
          properties:
            notification:
              $ref: '#/components/schemas/NotificationResponseObject'

    NotificationResponseMulti:
      allOf:
        - type: object
          description: List of found notifications
          properties:
            notifications:
              type: array
              items:
                $ref: '#/components/schemas/NotificationResponseObject'

    NotificationCreateResponse:
      allOf:
        - $ref: '#/components/schemas/IResponse'
        - $ref: '#/components/schemas/NotificationResponseSingle'

    NotificationReadResponse:
      allOf:
        - $ref: '#/components/schemas/IResponse'
        - $ref: '#/components/schemas/NotificationResponseSingle'

    NotificationUpdateResponse:
      allOf:
        - $ref: '#/components/schemas/IResponse'
        - $ref: '#/components/schemas/NotificationResponseSingle'

    NotificationCancelResponse:
      allOf:
        - $ref: '#/components/schemas/IResponse'
        - $ref: '#/components/schemas/NotificationResponseSingle'

    NotificationSearchResponse:
      allOf:
        - $ref: '#/components/schemas/IResponse'
        - $ref: '#/components/schemas/NotificationResponseMulti'

    # STUBS ======================
    NotificationRequestDebugMode:
      type: string
      enum:
        - prod
        - test
        - stub

    NotificationRequestDebug:
      type: object
      properties:
        debug:
          $ref: '#/components/schemas/NotificationDebug'

    NotificationDebug:
      type: object
      properties:
        mode:
          $ref: '#/components/schemas/NotificationRequestDebugMode'
        stub:
          $ref: '#/components/schemas/NotificationRequestDebugStubs'

    NotificationRequestDebugStubs:
      type: string
      description: Stubs for mocking and debugging
      enum:
        - success
        - notFound
        - badId
        - badTitle
        - badDescription
        - badVisibility
        - cannotCancel
        - badSearchString
